### ISSUE TITLE
Data not persisted in volume after stopping the docker container of Lowkey Vault

### ISSUE THREAD

**Issue by git-fudge** [nagyesta/lowkey-vault#411] opened 2023-01-10 07:29 UTC
#### Describe the bug

After stopping the container using docker-compose down. The volume created is not retaining the data stored in the Lowkey Vault.

#### To reproduce

1. Go to the directory of docker-compose file
2. Run the command "docker-compose up"
3. Store any secret in the Lowkey Vault
4. Stop the execution using "docker-compose down"
5. Start execution again using "docker-compose up"
6. Previously stored secrets are not available when retrieving secrets through api.

#### Expected behavior

Secrets should persist in the volume created by docker.

#### Actual behavior

Secrets are not being persisted

#### Environment

- OS: Windows

**Comment by nagyesta** [comment] 2023-01-10 18:21
Hi @git-fudge ,
First of all, thank you for using Lowkey Vault as well as taking the time and reporting this issue! I have taken a look at what you have described and it looks like you have ran into a side-effect of using an in-memory data store (as Lowkey Vault is only storing things in memory). Due to this, I wouldn't describe this behavior as a bug since data is not supposed to be persisted to disk. This is by design in order to make it simple to throw away previously altered state after the test runs.

With that said, no need to worry, I think your use case could still be supported if the following things are true:

1. The local application using Lowkey Vault expects the same secret values to be present at start-up
2. The local application does not need to add/alter secret values (i.e. Lowkey Vault does not need to keep any changes compared to the known working baseline required by a successful application start-up)

If these are true, you could follow the steps mentioned [here](https://github.com/nagyesta/lowkey-vault/wiki/Example:-Importing-vault-contents-at-startup) and prepare your vault once, then [export](https://github.com/nagyesta/lowkey-vault/wiki/Example:-Importing-vault-contents-at-startup#3-export-content) the contents manually and make sure to [import](https://github.com/nagyesta/lowkey-vault/wiki/Example:-Importing-vault-contents-at-startup#5-import-your-file-when-the-container-starts) the previously exported content as import file when Lowkey Vault is started.

Do you think this could work for you? If not, could you please share a bit more about your use case in order to let me come up with a better recommendation?

**Comment by nagyesta** [comment] 2023-01-16 10:09
Hi @git-fudge ,
I assume your issue is mitigated with the approach I have provided above. Please let me know in case it is still a problem. I will close this ticket and consider it to be "solved" on the weekend if you have no objections.

**Comment by nagyesta** [comment] 2023-01-22 09:56
Closing, please reopen in case the problem is still not mitigated.

**Closed by nagyesta** 2023-01-22 09:56 UTC
Labels: bug, community requested

**Comment by nagyesta** [comment] 2025-05-08 19:24
Hi @piyush429 ,
I know it was a long time ago, but I wanted to let you know just in case, that the latest version (`v3.1.0`) added support for persisting data automatically after each change. As far as I see, this could be interesting for your use-case as well (if nothing changed since you have opened this ticket).
All the best!
